 [A B C D]=linmod('talle2y')
sys=ss(A, B, C, D)
[num,den]=ss2tf(A, B, C, D)
sys2=tf(num,den)
%sysfb=feedback(sys,1)
%step(sysfb)
figure(2)
step(sys)
figure(3)
%plot(tm,w)
%figure(4)
rlocus(sys)